/**
 * ثوابت المشروع
 */

// أنواع تطبيقات الموبايل المدعومة
const MOBILE_APP_TYPES = {
    FLUTTER: 'flutter',
    XAMARIN: 'xamarin',
    NATIVE_ANDROID: 'nativeAndroid',
    NATIVE_IOS: 'nativeIOS',
    REACT_NATIVE: 'reactNative',
};

// فئات المخاطر الرئيسية
const RISK_CATEGORIES = {
    SECURITY: 'security',
    PERFORMANCE: 'performance',
    MEMORY: 'memory',
    BATTERY: 'battery',
};

// مستويات شدة المخاطر
const SEVERITY_LEVELS = {
    CRITICAL: 'critical',
    HIGH: 'high',
    MEDIUM: 'medium',
    LOW: 'low',
    INFO: 'info',
};

// مخاطر الأمان المستهدفة
const SECURITY_RISKS = {
    M1_IMPROPER_CREDENTIAL_USAGE: 'M1: Improper Credential Usage',
    M2_INADEQUATE_SUPPLY_CHAIN: 'M2: Inadequate Supply Chain Security',
    M3_INSECURE_AUTH: 'M3: Insecure Authentication/Authorization',
    M4_INSUFFICIENT_VALIDATION: 'M4: Insufficient Input/Output Validation',
    M5_INSECURE_COMMUNICATION: 'M5: Insecure Communication',
    M6_INADEQUATE_PRIVACY: 'M6: Inadequate Privacy Controls',
    M7_INSUFFICIENT_BINARY_PROTECTIONS: 'M7: Insufficient Binary Protections',
    M8_SECURITY_MISCONFIGURATION: 'M8: Security Misconfiguration',
    M9_INSECURE_DATA_STORAGE: 'M9: Insecure Data Storage',
    M10_INSUFFICIENT_CRYPTOGRAPHY: 'M10: Insufficient Cryptography',
    DATA_LEAKAGE: 'Data Leakage',
    HARDCODED_SECRETS: 'Hardcoded Secrets',
    INSECURE_ACCESS_CONTROL: 'Insecure Access Control',
    PATH_TRAVERSAL: 'Path Overwrite and Path Traversal',
    UNPROTECTED_ENDPOINTS: 'Unprotected Endpoints',
    UNSAFE_SHARING: 'Unsafe Sharing',
    M11_WEAK_PASSWORD_POLICY: 'M11: Weak Password Policy',
    M12_ABSENT_ACCOUNT_LOCKOUT: 'M12: Absent Account Lockout',
    M13_UNSECURED_API: 'M13: Unsecured API',
    M14_EXCESSIVE_PRIVILEGES: 'M14: Excessive Privileges',
    M15_INSUFFICIENT_LOGGING: 'M15: Insufficient Logging and Monitoring',
    M16_UNVERIFIED_INPUT: 'M16: Unverified Input Handling',
    M17_DISPOSABLE_CREDENTIALS: 'M17: Disposable Credentials',
    M18_FAILURE_TO_ENCRYPT: 'M18: Failure to Encrypt Sensitive Data',
    M19_INSUFFICIENT_ACCESS_CONTROLS: 'M19: Insufficient Access Controls',
    M20_MISSING_SOFTWARE_UPDATES: 'M20: Missing Software Updates',
    M21_VULNERABLE_DEPENDENCIES: 'M21: Vulnerable Dependencies',
    M22_RELIANCE_ON_OUTDATED_PROTOCOLS: 'M22: Reliance on Outdated Protocols',
    M23_WEAK_HASHING_ALGORITHMS: 'M23: Weak Hashing Algorithms',
    M24_UNVALIDATED_REDIRECTS: 'M24: Unvalidated Redirects and Forwards',
    M25_UNSECURED_HOSTING: 'M25: Unsecured Hosting Environment',
    M26_INSECURE_CONFIGURATION: 'M26: Insecure Configuration Management',
    M27_LACK_OF_BIOMETRICS: 'M27: Lack of Biometrics Authentication',
    M28_MISSING_FIREWALL_RULES: 'M28: Missing Firewall Rules',
    M29_INSUFFICIENT_DATA_RETENTION: 'M29: Insufficient Data Retention Practices',
    M30_LACK_OF_MULTI_FACTOR_AUTH: 'M30: Lack of Multi-Factor Authentication',
    M31_UNPROTECTED_CREDENTIAL_STORAGE: 'M31: Unprotected Credential Storage',
    M32_SENSITIVE_DATA_EXPOSURE: 'M32: Sensitive Data Exposure',
    M33_ACCESSIBLE_BACKEND_SERVICES: 'M33: Accessible Backend Services',
    M34_VULNERABLE_SCRIPTS: 'M34: Vulnerable Client-Side Scripts',
    M35_INSECURE_SESSION_MANAGEMENT: 'M35: Insecure Session Management',
    M36_MISUSE_OF_PUBLIC_KEY_INFRASTRUCTURE: 'M36: Misuse of Public Key Infrastructure',
    M37_ANTI_REVERSE_ENGINEERING_WEAKNESS: 'M37: Anti-Reverse Engineering Weakness',
    M38_UNENCRYPTED_DATA_TRANSMISSION: 'M38: Unencrypted Data Transmission',
    M39_MISSING_CODE_OBFUSCATION: 'M39: Missing Code Obfuscation',
    M40_INSIDER_THREAT: 'M40: Insider Threat',
    M41_EXPOSURE_TO_RANSOMWARE: 'M41: Exposure to Ransomware Attacks',
    M42_LACK_OF_BUSINESS_CONTINUITY_PLAN: 'M42: Lack of Business Continuity Plan',
    M43_POOR_USER_ACCESS_MONITORING: 'M43: Poor User Access Monitoring',
    M44_SENSITIVE_CONFIGURATIONS_IN_SOURCE_CODE: 'M44: Sensitive Configurations in Source Code',
    M45_UNENCRYPTED_LOCAL_STORAGE: 'M45: Unencrypted Local Storage',
    M46_FAILURE_TO_ISOLATE_VULNERABLE_COMPONENTS: 'M46: Failure to Isolate Vulnerable Components',
    M47_UNRESTRICTED_FILE_UPLOAD: 'M47: Unrestricted File Upload Vulnerability',
    M48_LACK_OF_NETWORK_SEGMENTATION: 'M48: Lack of Network Segmentation',
    M49_WEAK_SESSION_EXPIRATION_POLICY: 'M49: Weak Session Expiration Policy',
    M50_MISSING_USER_ACTIVITY_LOGGING: 'M50: Missing User Activity Logging',
    M51_UNPROTECTED_VULNERABLE_SERVICES: 'M51: Unprotected Vulnerable Services',
    M52_UNDERLYING_SOFTWARE_VULNERABILITIES: 'M52: Underlying Software Vulnerabilities',
    M53_RISKY_USE_OF_THIRD_PARTY_SERVICES: 'M53: Risky Use of Third-Party Services',
    M54_INSUFFICIENT_ENDPOINT_SECURITY: 'M54: Insufficient Endpoint Security',
    M55_INSECURE_JAVA_SCRIPT_LIBRARY: 'M55: Insecure JavaScript Library',
    M56_WEAK_ENCRYPTION_KEYS: 'M56: Weak Encryption Keys',
    M57_RELYING_ON_DEFAULT_CREDENTIALS: 'M57: Relying on Default Credentials',
    M58_FRAUDULENT_ACCESS_ATTEMPTS: 'M58: Fraudulent Access Attempts',
    M59_MISMANAGED_SSL_CERTIFICATES: 'M59: Mismanaged SSL Certificates',
    M60_SENSITIVE_DATA_ON_SHARED_HOSTING: 'M60: Sensitive Data on Shared Hosting',
    M61_RISKY_USE_OF_STATIC_KEYS: 'M61: Risky Use of Static Keys',
    M62_MISSING_CROSS_SITE_REQUEST_FORGERY_PROTECTION: 'M62: Missing CSRF Protection',
    M63_POOR_PASSWORD_STORAGE: 'M63: Poor Password Storage Practices',
    M64_WEAK_SESSION_KEYS: 'M64: Weak Session Keys',
    M65_OVEREXPOSED_DEBUG_INFORMATION: 'M65: Overexposed Debug Information',
    M66_OLD_SOFTWARE_VERSIONS_IN_PRODUCTION: 'M66: Old Software Versions in Production',
    M67_WEAK_RANDOM_NUMBER_GENERATION: 'M67: Weak Random Number Generation',
    M68_INSUFFICIENT_CODE_REVIEW_PROCESSES: 'M68: Insufficient Code Review Processes',
    M69_MISSING_SECURE_CODING_GUIDELINES: 'M69: Missing Secure Coding Guidelines',
    M70_MISCONFIGURED_REVERSE_PROXY: 'M70: Misconfigured Reverse Proxy',
    M71_INSECURE_RDP_ACCESS: 'M71: Insecure Remote Desktop Protocol (RDP) Access',
    M72_UNAUTHORIZED_MOBILE_APP_ACCESS: 'M72: Unauthorized Mobile App Access',
    M73_UNSECURED_NO_SQL_DATABASES: 'M73: Unsecured NoSQL Databases',
    M74_MISSING_XSS_PROTECTION: 'M74: Missing Cross-Site Scripting (XSS) Protection',
    M75_MISUSED_CLOUD_SERVICES: 'M75: Misused Cloud Services',
    M76_UNSECURED_ADMIN_INTERFACES: 'M76: Unsecured Admin Interfaces',
    M77_INSUFFICIENT_UPDATE_POLICY: 'M77: Insufficient Update Policy Enforcement',
    M78_UNPROTECTED_PERSONAL_DATA: 'M78: Unprotected Personal Data',
    M79_MISSING_SECURE_COOKIES: 'M79: Missing Secure Cookies',
    M80_UNSAFE_DATABASE_ACCESS: 'M80: Unsafe Database Access',
    M81_MISCONFIGURED_ACCESS_KEYS: 'M81: Misconfigured Access Keys',
    M82_NO_TLS_CERTIFICATE_VALIDATION: 'M82: No TLS Certificate Validation',
    M83_WEAK_ACCESS_CONTROL_LISTS: 'M83: Weak Access Control Lists',
    M84_UNSAFE_HTTPS_CONFIGURATION: 'M84: Unsafe HTTPS Configuration',
    M85_INSUFFICIENT_FIREWALL_CONFIGURATION: 'M85: Insufficient Firewall Configuration',
    M86_MISSING_INPUT_SANITATION: 'M86: Missing Input Sanitization',
    M87_UNSAFE_FILE_DOWNLOADS: 'M87: Unsafe File Downloads',
    M88_INADEQUATE_SCANNING_FOR_VIRUSES: 'M88: Inadequate Virus Scanning',
    M89_FALLBACK_TO_INSECURE_PROTOCOLS: 'M89: Fallback to Insecure Protocols',
    M90_EXPOSURE_TO_DENIAL_OF_SERVICE_ATTACKS: 'M90: Exposure to Denial of Service Attacks',
    M91_MISSING_MFA_FOR_CRITICAL_ACTIONS: 'M91: Missing Multi-Factor Authentication for Critical Actions',
    M92_UNPROTECTED_SENSITIVE_API_KEYS: 'M92: Unprotected Sensitive API Keys',
    M93_UNSAFE_CACHING_POLICY: 'M93: Unsafe Caching Policy',
    M94_UNRESTRICTED_ACCESS_TO_CONFIDENTIAL_INFORMATION: 'M94: Unrestricted Access to Confidential Information',
    M95_UNSECURED_BACKDOOR_ACCOUNTS: 'M95: Unsecured Backdoor Accounts',
    M96_UNVALIDATED_FILE_INPUT: 'M96: Unvalidated File Input',
    M97_WEAK_FIREWALL_POLICIES: 'M97: Weak Firewall Policies',
    M98_EXPOSED_API_KEYS: 'M98: Exposed API Keys',
    M99_UNSECURED_LOGGING: 'M99: Unsecured Logging',
    M100_LACK_OF_TRAFFIC_ENCRYPTION: 'M100: Lack of Traffic Encryption'
};


// مخاطر تطبيقات المحمول
const MOBILE_RISKS = {
    M1_IMPROPER_PLATFORM_USAGE: 'M1: Improper Platform Usage',
    M2_INSECURE_DATA_STORAGE: 'M2: Insecure Data Storage',
    M3_INSECURE_COMMUNICATION: 'M3: Insecure Communication',
    M4_INSECURE_AUTHENTICATION: 'M4: Insecure Authentication',
    M5_INSUFFICIENT_CRYPTOGRAPHY: 'M5: Insufficient Cryptography',
    M6_INSECURE_AUTHORIZATION: 'M6: Insecure Authorization',
    M7_CLIENT_CODE_QUALITY: 'M7: Client Code Quality',
    M8_CODE_TAMPERING: 'M8: Code Tampering',
    M9_REVERSE_ENGINEERING: 'M9: Reverse Engineering',
    M10_EXTRANEOUS_FUNCTIONALITY: 'M10: Extraneous Functionality',
    M11_MALICIOUS_APP_DOWNLOADS: 'M11: Malicious App Downloads',
    M12_LACK_OF_ENCRYPTION: 'M12: Lack of Encryption',
    M13_INSECURE_API_ACCESS: 'M13: Insecure API Access',
    M14_UNPROTECTED_USER_SESSION: 'M14: Unprotected User Session',
    M15_UNSAFE_FILE_UPLOADS: 'M15: Unsafe File Uploads',
    M16_INSUFFICIENT_USER_PRIVILEGES: 'M16: Insufficient User Privileges',
    M17_VULNERABLE_THIRD_PARTY_LIBRARIES: 'M17: Vulnerable Third-Party Libraries',
    M18_WEAK_SESSION_MANAGEMENT: 'M18: Weak Session Management',
    M19_UNENCRYPTED_LOCAL_STORAGE: 'M19: Unencrypted Local Storage',
    M20_EXPOSED_API_KEYS: 'M20: Exposed API Keys',
    M21_SENSITIVE_DATA_LEAKAGE: 'M21: Sensitive Data Leakage',
    M22_MISSING_TWO_FACTOR_AUTH: 'M22: Missing Two-Factor Authentication',
    M23_BAD_SSL_CONFIGURATION: 'M23: Bad SSL Configuration',
    M24_WEAK_PASSWORD_POLICY: 'M24: Weak Password Policy',
    M25_UNPROTECTED_LOG_FILES: 'M25: Unprotected Log Files',
    M26_INSUFFICIENT_APP_PERMISSION: 'M26: Insufficient App Permission',
    M27_EXPOSURE_TO_RANSOMWARE: 'M27: Exposure to Ransomware',
    M28_SENSITIVE_STORAGE_ON_UNTRUSTED_MEDIA: 'M28: Sensitive Storage on Untrusted Media',
    M29_THIRD_PARTY_CODE_INJECTION: 'M29: Third-Party Code Injection',
    M30_INSECURE_MOBILE_WEB_VIEW: 'M30: Insecure Mobile Web View',
    M31_LACK_OF_MOBILE_APP_SECURITY_TESTING: 'M31: Lack of Mobile App Security Testing',
    M32_UNRESTRICTED_API_ACCESS: 'M32: Unrestricted API Access',
    M33_MALICIOUS_AD_INJECTION: 'M33: Malicious Ad Injection',
    M34_APP_PERMISSION_BYPASS: 'M34: App Permission Bypass',
    M35_UNVALIDATED_REDIRECTS: 'M35: Unvalidated Redirects',
    M36_EXPOSED_INTENT_FILTERS: 'M36: Exposed Intent Filters',
    M37_IMPROPER_ERROR_HANDLING: 'M37: Improper Error Handling',
    M38_UNNECESSARY_BROADCAST_RECEIVERS: 'M38: Unnecessary Broadcast Receivers',
    M39_LOOSELY_DEFINED_CONTENT_PROVIDER_PERMISSIONS: 'M39: Loosely Defined Content Provider Permissions',
    M40_INSECURE_DISTRIBUTION_CHANNEL: 'M40: Insecure Distribution Channel',
    M41_UNENCRYPTED_PASSWORD_STORAGE: 'M41: Unencrypted Password Storage',
    M42_UNSAFE_BROADCAST_RECEIVER: 'M42: Unsafe Broadcast Receiver',
    M43_LOOSELY_DEFINED_SHARED_PREFERENCES: 'M43: Loosely Defined Shared Preferences',
    M44_MISSING_DEVICE_ENCRYPTION: 'M44: Missing Device Encryption',
    M45_MISCONFIGURED_SECURITY_HEADERS: 'M45: Misconfigured Security Headers',
    M46_ABSENT_REMOTE_AUTHORIZATION: 'M46: Absent Remote Authorization',
    M47_MALICIOUS_CODE_OBFUSCATION: 'M47: Malicious Code Obfuscation',
    M48_EXCESSIVE_APP_PERMISSIONS: 'M48: Excessive App Permissions',
    M49_MISSING_INPUT_SANITIZATION: 'M49: Missing Input Sanitization',
    M50_UNSAFE_BROWSER_STORAGE: 'M50: Unsafe Browser Storage',
    M51_WEAK_SSL_CERTIFICATE_VALIDATION: 'M51: Weak SSL Certificate Validation',
    M52_EXPOSURE_TO_PRIVACY_VIOLATIONS: 'M52: Exposure to Privacy Violations',
    M53_UNNECESSARY_ROOT_ACCESS: 'M53: Unnecessary Root Access',
    M54_IMPROPER_STORAGE_OF_AUTH_TOKENS: 'M54: Improper Storage of Auth Tokens',
    M55_LACK_OF_USER_ACTIVITY_MONITORING: 'M55: Lack of User Activity Monitoring',
    M56_INADEQUATE_API_RATE_LIMITING: 'M56: Inadequate API Rate Limiting',
    M57_EXPOSED_DEBUGGING_INTERFACES: 'M57: Exposed Debugging Interfaces',
    M58_CROSS_SITE_SCRIPTING_VULNERABILITY: 'M58: Cross-Site Scripting Vulnerability',
    M59_INSUFFICIENT_INPUT_VALIDATION: 'M59: Insufficient Input Validation',
    M60_UNSAFE_NETWORK_CONFIGURATION: 'M60: Unsafe Network Configuration',
    M61_MISSING_SESSION_TIMEOUT_POLICY: 'M61: Missing Session Timeout Policy',
    M62_INSUFFICIENT_OBFUSCATION: 'M62: Insufficient Obfuscation',
    M63_UNSECURE_PASSWORD_RESET_PROCESS: 'M63: Unsecure Password Reset Process',
    M64_WEAK_COOKIE_SECURITY: 'M64: Weak Cookie Security',
    M65_LACK_OF_PROTECTION_AGAINST_MAN_IN_THE_MIDDLE: 'M65: Lack of Protection Against Man-in-the-Middle',
    M66_UNSECURED_CODE_SIGNING: 'M66: Unsecured Code Signing',
    M67_APP_STORE_VULNERABILITIES: 'M67: App Store Vulnerabilities',
    M68_LOOSELY_DEFINED_FILE_PERMISSIONS: 'M68: Loosely Defined File Permissions',
    M69_MISSING_FILE_INTEGRITY_CHECKS: 'M69: Missing File Integrity Checks',
    M70_WEAK_KEY_GENERATION: 'M70: Weak Key Generation',
    M71_ABSENT_SESSION_ID_SECURITY: 'M71: Absent Session ID Security',
    M72_WEAK_RSA_KEY_USAGE: 'M72: Weak RSA Key Usage',
    M73_MALICIOUS_LIBRARY_INCLUSION: 'M73: Malicious Library Inclusion',
    M74_INSECURE_HTTP_HEADERS: 'M74: Insecure HTTP Headers',
    M75_UNPROTECTED_SHARED_PREFS: 'M75: Unprotected Shared Preferences',
    M76_MISSING_EXPIRATION_TIMESTAMPS: 'M76: Missing Expiration Timestamps',
    M77_INSECURE_TOKEN_STORAGE: 'M77: Insecure Token Storage',
    M78_INSUFFICIENT_APP_SECURITY_UPDATES: 'M78: Insufficient App Security Updates',
    M79_UNRESTRICTED_ACCESS_TO_INTERNAL_STORAGE: 'M79: Unrestricted Access to Internal Storage',
    M80_MISSING_PROPER_ACCESS_CONTROL: 'M80: Missing Proper Access Control',
    M81_LACK_OF_TRAFFIC_MONITORING: 'M81: Lack of Traffic Monitoring',
    M82_INSUFFICIENT_SESSION_ENCRYPTION: 'M82: Insufficient Session Encryption',
    M83_UNSAFE_LOGGING_OF_USER_DATA: 'M83: Unsafe Logging of User Data',
    M84_EXPOSED_SENSITIVE_API_ENDPOINTS: 'M84: Exposed Sensitive API Endpoints',
    M85_IMPROPER_USE_OF_TRUSTED_CERTIFICATES: 'M85: Improper Use of Trusted Certificates',
    M86_WEAK_IMAGE_ENCRYPTION: 'M86: Weak Image Encryption',
    M87_MALICIOUS_USB_ACCESS: 'M87: Malicious USB Access',
    M88_INSUFFICIENT_FILE_PERMISSION: 'M88: Insufficient File Permission',
    M89_UNPROTECTED_APP_UPDATES: 'M89: Unprotected App Updates',
    M90_INSECURE_CACHE_STORAGE: 'M90: Insecure Cache Storage',
    M91_MALICIOUS_DATA_EXFILTRATION: 'M91: Malicious Data Exfiltration',
    M92_UNSECURED_DEVICE_SETTINGS: 'M92: Unsecured Device Settings',
    M93_WEAK_APP_DEBUGGING: 'M93: Weak App Debugging',
    M94_MALICIOUS_NETWORK_INTERCEPTIONS: 'M94: Malicious Network Interceptions',
    M95_UNTRUSTED_REMOTE_SERVICES: 'M95: Untrusted Remote Services',
    M96_IMPROPER_APP_LOGGING: 'M96: Improper App Logging',
    M97_UNSAFE_BLUETOOTH_CONNECTIVITY: 'M97: Unsafe Bluetooth Connectivity',
    M98_INSUFFICIENT_BUFFER_OVERFLOW_PROTECTION: 'M98: Insufficient Buffer Overflow Protection',
    M99_POOR_USER_ACCESS_MANAGEMENT: 'M99: Poor User Access Management',
    M100_MALICIOUS_REMOTE_CODE_EXECUTION: 'M100: Malicious Remote Code Execution'
};


// مخاطر تطبيقات المحمول 2014
const MOBILE_RISKS_2014 = {
    M1_WEAK_SERVER_SIDE_CONTROLS: 'M1: Weak Server Side Controls',
    M2_INSECURE_DATA_STORAGE: 'M2: Insecure Data Storage',
    M3_INSUFFICIENT_TRANSPORT_PROTECTION: 'M3: Insufficient Transport Layer Protection',
    M4_UNINTENDED_DATA_LEAKAGE: 'M4: Unintended Data Leakage',
    M5_POOR_AUTHORIZATION: 'M5: Poor Authorization and Authentication',
    M6_BROKEN_CRYPTOGRAPHY: 'M6: Broken Cryptography',
    M7_CLIENT_SIDE_INJECTION: 'M7: Client Side Injection',
    M8_SECURITY_DECISIONS_UNTRUSTED_INPUTS: 'M8: Security Decisions Via Untrusted Inputs',
    M9_IMPROPER_SESSION_HANDLING: 'M9: Improper Session Handling',
    M10_LACK_BINARY_PROTECTIONS: 'M10: Lack of Binary Protections',
    M11_UNSECURED_CREDENTIALS_STORAGE: 'M11: Unsecured Credentials Storage',
    M12_INADEQUATE_SESSION_TIMEOUTS: 'M12: Inadequate Session Timeouts',
    M13_EXPOSURE_TO_MALICIOUS_APPS: 'M13: Exposure to Malicious Apps',
    M14_UNSAFE_MOBILE_BROWSING: 'M14: Unsafe Mobile Browsing',
    M15_UNPROTECTED_API_KEYS: 'M15: Unprotected API Keys',
    M16_MISSING_APP_PERMISSIONS: 'M16: Missing App Permissions Validation',
    M17_WEAK_ENCRYPTION_SCHEMES: 'M17: Weak Encryption Schemes',
    M18_LACK_OF_MULTI_FACTOR_AUTHENTICATION: 'M18: Lack of Multi-Factor Authentication',
    M19_UNSECURED_CONNECTIONS: 'M19: Unsecured Connections',
    M20_WEAK_PASSWORDS: 'M20: Weak Passwords',
    M21_LACK_OF_INPUT_SANITIZATION: 'M21: Lack of Input Sanitization',
    M22_INSECURE_DATA_TRANSFERS: 'M22: Insecure Data Transfers',
    M23_UNSECURED_SHARED_PREFERENCES: 'M23: Unsecured Shared Preferences',
    M24_POOR_APP_SECURITY_POLICY: 'M24: Poor App Security Policy',
    M25_MALICIOUS_CODE_INJECTION: 'M25: Malicious Code Injection',
    M26_APP_VULNERABILITIES: 'M26: App Vulnerabilities',
    M27_UNPROTECTED_FILE_STORAGE: 'M27: Unprotected File Storage',
    M28_INSECURE_LOCAL_STORAGE: 'M28: Insecure Local Storage',
    M29_UNENCRYPTED_DATA_STORAGE: 'M29: Unencrypted Data Storage',
    M30_INADEQUATE_FIREWALL_CONFIGURATION: 'M30: Inadequate Firewall Configuration',
    M31_POOR_SESSION_MANAGEMENT: 'M31: Poor Session Management',
    M32_LACK_OF_REVERSE_PROXY_CONFIGURATION: 'M32: Lack of Reverse Proxy Configuration',
    M33_EXCESSIVE_APP_PERMISSIONS: 'M33: Excessive App Permissions',
    M34_EXPOSED_BROADCAST_RECEIVERS: 'M34: Exposed Broadcast Receivers',
    M35_BYPASSING_AUTHORIZATION: 'M35: Bypassing Authorization',
    M36_MISUSE_OF_INTENT_FILTERS: 'M36: Misuse of Intent Filters',
    M37_UNRESTRICTED_ACCESS_TO_CONTENT_PROVIDERS: 'M37: Unrestricted Access to Content Providers',
    M38_UNSAFE_SESSION_STORAGE: 'M38: Unsafe Session Storage',
    M39_WEAK_KEYSTORE_CONFIGURATION: 'M39: Weak Keystore Configuration',
    M40_EXPOSURE_TO_DENIAL_OF_SERVICE: 'M40: Exposure to Denial of Service',
    M41_VULNERABLE_PUSH_NOTIFICATION: 'M41: Vulnerable Push Notification',
    M42_POOR_CRYPTOGRAPHIC_KEY_STORAGE: 'M42: Poor Cryptographic Key Storage',
    M43_UNENCRYPTED_LOGGING: 'M43: Unencrypted Logging',
    M44_MISSING_ENCRYPTION_FOR_SENSITIVE_DATA: 'M44: Missing Encryption for Sensitive Data',
    M45_INSUFFICIENT_USER_ACCESS_CONTROL: 'M45: Insufficient User Access Control',
    M46_MISCONFIGURED_API_ENDPOINTS: 'M46: Misconfigured API Endpoints',
    M47_MISSING_VALIDATION_FOR_EXTERNAL_INPUT: 'M47: Missing Validation for External Input',
    M48_INSECURE_CODE_SIGNING: 'M48: Insecure Code Signing',
    M49_POOR_AUTHENTICATION_MECHANISMS: 'M49: Poor Authentication Mechanisms',
    M50_LACK_OF_NETWORK_ISOLATION: 'M50: Lack of Network Isolation',
    M51_WEAK_SSL_TLS_IMPLEMENTATION: 'M51: Weak SSL/TLS Implementation',
    M52_EXPOSURE_OF_SESSIONS_THROUGH_COOKIES: 'M52: Exposure of Sessions Through Cookies',
    M53_UNSAFE_FILE_PERMISSIONS: 'M53: Unsafe File Permissions',
    M54_INADEQUATE_REVERSE_ENGINEERING_PROTECTION: 'M54: Inadequate Reverse Engineering Protection',
    M55_UNPROTECTED_USER_TOKENS: 'M55: Unprotected User Tokens',
    M56_MISSING_SECURITY_UPDATES: 'M56: Missing Security Updates',
    M57_VULNERABLE_THIRD_PARTY_LIBRARIES: 'M57: Vulnerable Third-Party Libraries',
    M58_APP_PRIVACY_LEAKS: 'M58: App Privacy Leaks',
    M59_UNAUTHORIZED_NETWORK_ACCESS: 'M59: Unauthorized Network Access',
    M60_INSECURE_WEBVIEW_CONFIGURATION: 'M60: Insecure WebView Configuration',
    M61_EXPOSURE_OF_USER_IDENTIFIERS: 'M61: Exposure of User Identifiers',
    M62_IMPROPER_ACCESS_TO_ENCRYPTED_DATA: 'M62: Improper Access to Encrypted Data',
    M63_UNSECURED_CRYPTOGRAPHIC_ALGORITHMS: 'M63: Unsecured Cryptographic Algorithms',
    M64_WEAK_HASHING_ALGORITHMS: 'M64: Weak Hashing Algorithms',
    M65_POOR_USER_BEHAVIOR_ANALYSIS: 'M65: Poor User Behavior Analysis',
    M66_MISSING_SESSION_ID_RENEWAL: 'M66: Missing Session ID Renewal',
    M67_IMPROPER_USE_OF_API_TOKENS: 'M67: Improper Use of API Tokens',
    M68_INSUFFICIENT_DATA_ENCRYPTION: 'M68: Insufficient Data Encryption',
    M69_POORLY_MANAGED_ACCESS_TOKENS: 'M69: Poorly Managed Access Tokens',
    M70_MISCONFIGURED_FIREWALL: 'M70: Misconfigured Firewall',
    M71_LACK_OF_BUFFER_OVERFLOW_PROTECTION: 'M71: Lack of Buffer Overflow Protection',
    M72_MALICIOUS_ACCESS_TO_LOG_FILES: 'M72: Malicious Access to Log Files',
    M73_WEAK_KEY_MANAGEMENT: 'M73: Weak Key Management',
    M74_UNRESTRICTED_REMOTE_ACCESS: 'M74: Unrestricted Remote Access',
    M75_MISSING_VERIFICATION_FOR_CODE_UPDATES: 'M75: Missing Verification for Code Updates',
    M76_INSECURE_MOBILE_BROWSERS: 'M76: Insecure Mobile Browsers',
    M77_UNSECURED_ANDROID_MANIFEST: 'M77: Unsecured Android Manifest',
    M78_MISSING_PRIVACY_POLICY: 'M78: Missing Privacy Policy',
    M79_UNSECURED_FILE_UPLOADS: 'M79: Unsecured File Uploads',
    M80_LACK_OF_DATA_RETENTION_POLICY: 'M80: Lack of Data Retention Policy',
    M81_UNSECURED_APP_COMMUNICATION: 'M81: Unsecured App Communication',
    M82_WEAK_SESSION_MANAGEMENT_POLICY: 'M82: Weak Session Management Policy',
    M83_MISSING_KEYSTORE_ENCRYPTION: 'M83: Missing Keystore Encryption',
    M84_UNPROTECTED_SERVER_ENDPOINTS: 'M84: Unprotected Server Endpoints',
    M85_LACK_OF_CORS_IMPLEMENTATION: 'M85: Lack of CORS Implementation',
    M86_INADEQUATE_USER_AUTHORIZATION: 'M86: Inadequate User Authorization',
    M87_UNSAFE_CUSTOM_CERTIFICATES: 'M87: Unsafe Custom Certificates',
    M88_LACK_OF_PROPER_SECURITY_LOGGING: 'M88: Lack of Proper Security Logging',
    M89_MISCONFIGURED_TOKEN_STORAGE: 'M89: Misconfigured Token Storage',
    M90_EXPOSURE_OF_PRIVATE_KEY: 'M90: Exposure of Private Key',
    M91_INSUFFICIENT_API_SECURITY_MEASURES: 'M91: Insufficient API Security Measures',
    M92_LACK_OF_ENCRYPTION_IN_MOBILE_APP_COMMUNICATION: 'M92: Lack of Encryption in Mobile App Communication',
    M93_UNAUTHORIZED_LOCAL_STORAGE_ACCESS: 'M93: Unauthorized Local Storage Access',
    M94_WEAK_OR_UNSAFE_ANDROID_PERMISSIONS: 'M94: Weak or Unsafe Android Permissions',
    M95_UNSECURED_LOGGING_IN_PRODUCTION: 'M95: Unsecured Logging in Production',
    M96_WEAK_CRYPTographic_KEY_MANAGEMENT: 'M96: Weak Cryptographic Key Management',
    M97_INADEQUATE_FILE_PERMISSION_PROTECTION: 'M97: Inadequate File Permission Protection',
    M98_MISSING_VULNERABILITY_SCANNING: 'M98: Missing Vulnerability Scanning',
    M99_POOR_API_THROTTLING: 'M99: Poor API Throttling',
    M100_UNPROTECTED_CONNECTIONS_ON_UNSECURED_NETWORKS: 'M100: Unprotected Connections on Unsecured Networks'
};


const APP_THREATS = {
    APP0_EAVESDROPPING: 'APP-0: Eavesdropping on Unencrypted App Traffic',
    APP1_MAN_IN_THE_MIDDLE: 'APP-1: Man-in-the-middle Attack on Server Authentication',
    APP2_SENSITIVE_INFO_EXPOSURE: 'APP-2: Sensitive Information Exposure',
    APP3_SENSITIVE_INFO_LOGS: 'APP-3: Sensitive Information in System Logs',
    APP4_WEAK_AUTHENTICATION: 'APP-4: Weak Authentication Mechanisms',
    APP5_INSECURE_DATA_STORAGE: 'APP-5: Insecure Data Storage on Device',
    APP6_UNSAFE_FILE_UPLOADS: 'APP-6: Unsafe File Uploads',
    APP7_INSECURE_API_ACCESS: 'APP-7: Insecure API Access',
    APP8_LACK_OF_INPUT_VALIDATION: 'APP-8: Lack of Input Validation',
    APP9_UNSECURED_SESSION_STORAGE: 'APP-9: Unsecured Session Storage',
    APP10_IMPROPER_ERROR_HANDLING: 'APP-10: Improper Error Handling',
    APP11_UNENCRYPTED_PASSWORD_STORAGE: 'APP-11: Unencrypted Password Storage',
    APP12_WEAK_CRYPTOGRAPHY: 'APP-12: Weak Cryptography for Data Encryption',
    APP13_POOR_SESSION_MANAGEMENT: 'APP-13: Poor Session Management Practices',
    APP14_MALICIOUS_CODE_INJECTION: 'APP-14: Malicious Code Injection',
    APP15_APP_PERMISSION_ESCALATION: 'APP-15: App Permission Escalation',
    APP16_MISSING_SSL_VERIFICATION: 'APP-16: Missing SSL/TLS Verification',
    APP17_EXPOSED_API_KEYS: 'APP-17: Exposed API Keys in Source Code',
    APP18_INSECURE_LOCAL_STORAGE: 'APP-18: Insecure Local Storage of Sensitive Data',
    APP19_WEAK_PASSWORD_POLICY: 'APP-19: Weak Password Policy',
    APP20_NO_MULTI_FACTOR_AUTH: 'APP-20: Lack of Multi-Factor Authentication',
    APP21_LACK_OF_AUTHORIZATION_CHECKS: 'APP-21: Lack of Authorization Checks',
    APP22_UNSAFE_WEBVIEW: 'APP-22: Unsafe WebView Configuration',
    APP23_MISSING_INPUT_SANITIZATION: 'APP-23: Missing Input Sanitization',
    APP24_INSECURE_FILE_ACCESS: 'APP-24: Insecure File Access on Device',
    APP25_UNSECURED_CLOUD_STORAGE: 'APP-25: Unsecured Cloud Storage Integration',
    APP26_WEAK_SSL_CONFIGURATION: 'APP-26: Weak SSL/TLS Configuration',
    APP27_INADEQUATE_APP_LOGGING: 'APP-27: Inadequate Application Logging and Monitoring',
    APP28_BYPASSING_ACCESS_CONTROL: 'APP-28: Bypassing Access Control',
    APP29_REVERSE_ENGINEERING: 'APP-29: Reverse Engineering of App Code',
    APP30_INSECURE_INTENT_FILTERS: 'APP-30: Insecure Intent Filters in Android Apps',
    APP31_UNSECURED_DATABASE_CONNECTIONS: 'APP-31: Unsecured Database Connections',
    APP32_LACK_OF_FIREWALL_CONFIGURATION: 'APP-32: Lack of Firewall Configuration in Mobile Apps',
    APP33_APP_VULNERABILITY_EXPLOITATION: 'APP-33: Exploitation of App Vulnerabilities',
    APP34_UNAUTHORIZED_ACCESS_TO_INTERNAL_STORAGE: 'APP-34: Unauthorized Access to Internal Storage',
    APP35_UNSAFE_LOGGING_OF_USER_DATA: 'APP-35: Unsafe Logging of User Data',
    APP36_MISSING_SECURE_CODING_PRACTICES: 'APP-36: Missing Secure Coding Practices',
    APP37_UNPROTECTED_BROADCAST_RECEIVERS: 'APP-37: Unprotected Broadcast Receivers in Android',
    APP38_UNSAFE_SHARED_PREFERENCES: 'APP-38: Unsafe Shared Preferences in Android',
    APP39_EXPOSURE_OF_SENSITIVE_INFO_IN_DEBUG_MODE: 'APP-39: Exposure of Sensitive Information in Debug Mode',
    APP40_INSECURE_CONTENT_PROVIDER: 'APP-40: Insecure Content Providers in Apps',
    APP41_UNSECURED_APP_CONFIGURATION: 'APP-41: Unsecured Application Configuration Files',
    APP42_MISCONFIGURED_APP_PERMISSIONS: 'APP-42: Misconfigured App Permissions',
    APP43_WEAK_KEYSTORE_ENCRYPTION: 'APP-43: Weak Keystore Encryption',
    APP44_LACK_OF_OBFUSCATION: 'APP-44: Lack of Code Obfuscation in App Code',
    APP45_UNSECURED_API_GATEWAY: 'APP-45: Unsecured API Gateway',
    APP46_EXPOSED_DEVICE_ID: 'APP-46: Exposed Device ID in App Logs',
    APP47_LACK_OF_USER_SESSION_TIMEOUTS: 'APP-47: Lack of User Session Timeouts',
    APP48_UNSECURED_NETWORK_CONFIGURATION: 'APP-48: Unsecured Network Configuration',
    APP49_WEAK_CLIENT_SIDE_VALIDATION: 'APP-49: Weak Client-Side Input Validation',
    APP50_UNSECURED_PUSH_NOTIFICATION: 'APP-50: Unsecured Push Notifications',
    APP51_UNSECURED_FILE_SHARING: 'APP-51: Unsecured File Sharing',
    APP52_LACK_OF_ACCESS_CONTROL: 'APP-52: Lack of Access Control to App Features',
    APP53_INADEQUATE_MEMORY_MANAGEMENT: 'APP-53: Inadequate Memory Management in Mobile Apps',
    APP54_WEAK_SESSION_KEYS: 'APP-54: Weak Session Keys',
    APP55_MALICIOUS_LIBRARY_INJECTION: 'APP-55: Malicious Library Injection',
    APP56_UNPROTECTED_APP_TOKENS: 'APP-56: Unprotected App Tokens',
    APP57_INADEQUATE_USER_AUTHENTICATION: 'APP-57: Inadequate User Authentication Process',
    APP58_MISSING_SECURE_APP_UPDATE: 'APP-58: Missing Secure App Update Mechanism',
    APP59_INSECURE_DATA_TRANSFER: 'APP-59: Insecure Data Transfer Between Devices',
    APP60_LACK_OF_SECURITY_MEASURES_FOR_FILE_STORAGE: 'APP-60: Lack of Security Measures for File Storage',
    APP61_WEAK_ENCRYPTION_FOR_PASSWORDS: 'APP-61: Weak Encryption for Passwords',
    APP62_POOR_LOGGING_OF_SECURITY_EVENTS: 'APP-62: Poor Logging of Security Events',
    APP63_UNSECURED_REMOVABLE_MEDIA_STORAGE: 'APP-63: Unsecured Removable Media Storage',
    APP64_INADEQUATE_ENCRYPTION_FOR_FILES: 'APP-64: Inadequate Encryption for Files',
    APP65_VULNERABLE_ANALYTICS_INTEGRATION: 'APP-65: Vulnerable Analytics Integration',
    APP66_INSECURE_DATABASE_QUERY_EXECUTION: 'APP-66: Insecure Database Query Execution',
    APP67_MISSING_OR_INADEQUATE_EXCEPTION_HANDLING: 'APP-67: Missing or Inadequate Exception Handling',
    APP68_UNPROTECTED_FILE_PERMISSIONS: 'APP-68: Unprotected File Permissions in Apps',
    APP69_LACK_OF_ENCRYPTION_FOR_FILES_IN_TRANSIT: 'APP-69: Lack of Encryption for Files in Transit',
    APP70_EXPOSURE_OF_SENSITIVE_FILES_IN_APP_STORAGE: 'APP-70: Exposure of Sensitive Files in App Storage',
    APP71_MISUSE_OF_PERMISSION_REQUESTS: 'APP-71: Misuse of Permission Requests',
    APP72_UNPROTECTED_NETWORK_ENDPOINTS: 'APP-72: Unprotected Network Endpoints',
    APP73_INSECURE_SHARING_OF_CREDENTIALS: 'APP-73: Insecure Sharing of Credentials',
    APP74_MISSING_APP_SECURITY_PATCHES: 'APP-74: Missing App Security Patches',
    APP75_INADEQUATE_AUTHENTICATION_FOR_SENSITIVE_ACTIONS: 'APP-75: Inadequate Authentication for Sensitive Actions',
    APP76_POOR_CLIENT_SIDE_STORAGE: 'APP-76: Poor Client-Side Storage Practices',
    APP77_UNPROTECTED_PERSONAL_INFORMATION: 'APP-77: Unprotected Personal Information',
    APP78_INSECURE_CLOUD_STORAGE: 'APP-78: Insecure Cloud Storage Integration',
    APP79_MISSING_MOBILE_APP_FIREWALL: 'APP-79: Missing Mobile App Firewall',
    APP80_INSECURE_REMOVABLE_MEDIA_ENCRYPTION: 'APP-80: Insecure Removable Media Encryption',
    APP81_UNSECURED_LOCAL_CACHE: 'APP-81: Unsecured Local Cache',
    APP82_MISSING_LOCAL_STORAGE_ENCRYPTION: 'APP-82: Missing Local Storage Encryption',
    APP83_INADEQUATE_REMOTE_AUTHORIZATION: 'APP-83: Inadequate Remote Authorization',
    APP84_UNPROTECTED_MOBILE_APP_SERVER: 'APP-84: Unprotected Mobile App Server',
    APP85_WEAK_DEVICE_SECURITY: 'APP-85: Weak Device Security Measures',
    APP86_UNAUTHORIZED_ACCESS_TO_SENSITIVE_DATA: 'APP-86: Unauthorized Access to Sensitive Data',
    APP87_POOR_FILE_SECURITY_CONFIGURATIONS: 'APP-87: Poor File Security Configurations',
    APP88_WEAK_NETWORK_SECURITY: 'APP-88: Weak Network Security Measures',
    APP89_UNSECURED_MOBILE_WEBVIEW: 'APP-89: Unsecured Mobile WebView Integration',
    APP90_LACK_OF_SESSION_EXPIRE_AFTER_INACTIVITY: 'APP-90: Lack of Session Expiry After Inactivity',
    APP91_UNSECURED_MOBILE_PAYMENT_SYSTEM: 'APP-91: Unsecured Mobile Payment System',
    APP92_INSECURE_FILE_SHARING_OVER_NETWORK: 'APP-92: Insecure File Sharing Over Network',
    APP93_EXPOSURE_OF_USER_DATA_VIA_APP_DEBUGGING: 'APP-93: Exposure of User Data Via App Debugging',
    APP94_INSECURE_USER_PROFILE_MANAGEMENT: 'APP-94: Insecure User Profile Management',
    APP95_WEAK_AUTHENTICATION_FOR_REMOTE_SERVICES: 'APP-95: Weak Authentication for Remote Services',
    APP96_UNSECURED_USER_LOGOUT: 'APP-96: Unsecured User Logout',
    APP97_INSECURE_THIRD_PARTY_INTEGRATIONS: 'APP-97: Insecure Third-Party Integrations',
    APP98_WEAK_SECURITY_FOR_FILE_SHARING: 'APP-98: Weak Security for File Sharing',
    APP99_INADEQUATE_SECURITY_FOR_API_KEYS: 'APP-99: Inadequate Security for API Keys',
    APP100_UNSECURED_MEDIA_STORAGE: 'APP-100: Unsecured Media Storage'
};


const PERFORMANCE_CATEGORIES = {
    UI_RESPONSIVENESS: 'UI Responsiveness',
    NETWORK_EFFICIENCY: 'Network Efficiency',
    COMPUTATION_EFFICIENCY: 'Computation Efficiency',
    RESOURCE_MANAGEMENT: 'Resource Management',
    STARTUP_TIME: 'Startup Time',
    MEMORY_USAGE: 'Memory Usage',
    CPU_UTILIZATION: 'CPU Utilization',
    BATTERY_CONSUMPTION: 'Battery Consumption',
    LOAD_TIME: 'Load Time',
    RESPONSE_TIME: 'Response Time',
    FRAME_RATE: 'Frame Rate',
    DATABASE_PERFORMANCE: 'Database Performance',
    CACHE_HIT_RATE: 'Cache Hit Rate',
    API_RESPONSE_TIME: 'API Response Time',
    THREAD_MANAGEMENT: 'Thread Management',
    I_O_PERFORMANCE: 'I/O Performance',
    ERROR_RATE: 'Error Rate',
    SCALABILITY: 'Scalability',
    CONCURRENCY: 'Concurrency',
    LATENCY: 'Latency',
    THROUGHOUT: 'Throughput',
    USER_EXPERIENCE: 'User Experience',
    MEMORY_LEAKS: 'Memory Leaks',
    NETWORK_LATENCY: 'Network Latency',
    SESSION_MANAGEMENT: 'Session Management',
    DATA_TRANSFER_RATE: 'Data Transfer Rate',
    FILE_IO_PERFORMANCE: 'File I/O Performance',
    DATABASE_QUERY_OPTIMIZATION: 'Database Query Optimization',
    NETWORK_PACKET_LOSS: 'Network Packet Loss',
    THREAD_POOL_USAGE: 'Thread Pool Usage',
    SUSPEND_RESUME_PERFORMANCE: 'Suspend/Resume Performance',
    LOAD_BALANCING: 'Load Balancing',
    APPLICATION_RESILIENCY: 'Application Resiliency',
    APPLICATION_SMOOTHNESS: 'Application Smoothness',
    ASYNC_TASK_EXECUTION: 'Async Task Execution',
    TASK_SCHEDULING: 'Task Scheduling',
    UI_DELAY: 'UI Delay',
    MEMORY_ALLOCATION: 'Memory Allocation',
    THREAD_SAFETY: 'Thread Safety',
    RESOURCE_LEAKS: 'Resource Leaks',
    GARBAGE_COLLECTION: 'Garbage Collection',
    MEMORY_COMPRESSION: 'Memory Compression',
    SLEEP_MODE_PERFORMANCE: 'Sleep Mode Performance',
    SYSTEM_HEALTH: 'System Health',
    PAGE_LOAD_TIME: 'Page Load Time',
    ASYNC_IO_PERFORMANCE: 'Async I/O Performance',
    OBJECT_POOLING: 'Object Pooling',
    NETWORK_BANDWIDTH: 'Network Bandwidth',
    DATABASE_CONNECTION_POOLING: 'Database Connection Pooling',
    MULTITHREADING_EFFICIENCY: 'Multithreading Efficiency',
    HARDWARE_ACCELERATION: 'Hardware Acceleration',
    SCREEN_REFRESH_RATE: 'Screen Refresh Rate',
    VIRTUAL_MEMORY_MANAGEMENT: 'Virtual Memory Management',
    RESPONSE_TIME_VS_CONCURRENCY: 'Response Time vs. Concurrency',
    HTTP_REQUEST_HANDLING: 'HTTP Request Handling',
    TASK_QUEUE_MANAGEMENT: 'Task Queue Management',
    BANDWIDTH_THROTTLING: 'Bandwidth Throttling',
    PROCESSOR_CACHE_USAGE: 'Processor Cache Usage',
    OS_SCHEDULING: 'OS Scheduling',
    API_CALL_THROUGHPUT: 'API Call Throughput',
    WORKER_THREAD_MANAGEMENT: 'Worker Thread Management',
    CONNECTION_POOLING: 'Connection Pooling',
    UI_SCALABILITY: 'UI Scalability',
    SERVICE_DISCOVERY: 'Service Discovery',
    SERVER_LOAD_MONITORING: 'Server Load Monitoring',
    DATABASE_INDEXING: 'Database Indexing',
    DATABASE_CACHING: 'Database Caching',
    THREAD_SYNCHRONIZATION: 'Thread Synchronization',
    API_RATE_LIMITING: 'API Rate Limiting',
    SERVER_THREAD_USAGE: 'Server Thread Usage',
    BACKGROUND_TASK_OPTIMIZATION: 'Background Task Optimization',
    CLIENT_SIDE_RENDERING: 'Client-side Rendering',
    SERVER_SIDE_RENDERING: 'Server-side Rendering',
    THREAD_PRIORITY: 'Thread Priority',
    IO_BOUND_TASKS: 'I/O Bound Tasks',
    SYSTEM_THREAD_COUNT: 'System Thread Count',
    PAGE_COMPRESSION: 'Page Compression',
    CACHING_STRATEGY: 'Caching Strategy',
    DATA_FETCHING_PERFORMANCE: 'Data Fetching Performance',
    GPU_ACCELERATION: 'GPU Acceleration',
    ERROR_HANDLING_PERFORMANCE: 'Error Handling Performance',
    NETWORK_RETRY_LOGIC: 'Network Retry Logic',
    THREAD_POOL_SIZE: 'Thread Pool Size',
    DATABASE_SHARDING: 'Database Sharding',
    BANDWIDTH_USAGE: 'Bandwidth Usage',
    CACHE_CONSISTENCY: 'Cache Consistency',
    CONNECTION_ESTABLISHMENT_TIME: 'Connection Establishment Time',
    RESPONSE_CACHING: 'Response Caching',
    TRANSACTION_MANAGEMENT: 'Transaction Management',
    DATA_REPLICATION: 'Data Replication',
    HIGH_AVAILABILITY: 'High Availability',
    DATABASE_REPLICATION: 'Database Replication',
    CROSS_THREAD_COMMUNICATION: 'Cross-thread Communication',
    UI_OPTIMIZATION: 'UI Optimization',
    FILE_COMPRESSION: 'File Compression',
    PERFORMANCE_BENCHMARKING: 'Performance Benchmarking',
    CONTENT_DELIVERY_OPTIMIZATION: 'Content Delivery Optimization',
    LOCAL_STORAGE_OPTIMIZATION: 'Local Storage Optimization',
    MEMORY_EFFICIENCY: 'Memory Efficiency',
    TASK_EXECUTION_TIME: 'Task Execution Time',
    CPU_OVERHEAD: 'CPU Overhead',
    SERVER_MONITORING: 'Server Monitoring',
    THREAD_POOL_MONITORING: 'Thread Pool Monitoring',
    SYSTEM_LOAD_MONITORING: 'System Load Monitoring',
    DATABASE_CONNECTIONS: 'Database Connections',
    SYSTEM_MEMORY_USAGE: 'System Memory Usage'
};


const MEMORY_CATEGORIES = {
    MEMORY_LEAKS: 'Memory Leaks',
    EXCESSIVE_MEMORY_USAGE: 'Excessive Memory Usage',
    INEFFICIENT_MEMORY_ALLOCATION: 'Inefficient Memory Allocation',
    MEMORY_FRAGMENTATION: 'Memory Fragmentation',
    MEMORY_OVERFLOW: 'Memory Overflow',
    MEMORY_CONSUMPTION_PEAKS: 'Memory Consumption Peaks',
    INSUFFICIENT_MEMORY_ALLOCATED: 'Insufficient Memory Allocated',
    MEMORY_THROTTLING: 'Memory Throttling',
    UNNECESSARY_MEMORY_ALLOCATIONS: 'Unnecessary Memory Allocations',
    MEMORY_CACHING_ISSUES: 'Memory Caching Issues',
    UNNECESSARY_MEMORY_CONSUMPTION: 'Unnecessary Memory Consumption',
    MEMORY_ACCESS_VIOLATIONS: 'Memory Access Violations',
    MEMORY_MANAGEMENT_FAILURES: 'Memory Management Failures',
    MEMORY_POOL_EXHAUSTION: 'Memory Pool Exhaustion',
    SUSPICIOUS_MEMORY_ALLOCATIONS: 'Suspicious Memory Allocations',
    UNRELEASED_MEMORY_RESOURCES: 'Unreleased Memory Resources',
    MEMORY_USAGE_MONITORING: 'Memory Usage Monitoring',
    MEMORY_EXPANSION_ISSUES: 'Memory Expansion Issues',
    MEMORY_LEAK_DETECTION_FAILURE: 'Memory Leak Detection Failure',
    INADEQUATE_MEMORY_CLEANUP: 'Inadequate Memory Cleanup',
    UNNECESSARY_MEMORY_COPYING: 'Unnecessary Memory Copying',
    DUPLICATE_MEMORY_ALLOCATION: 'Duplicate Memory Allocation',
    OVERALL_MEMORY_USAGE: 'Overall Memory Usage',
    MEMORY_ALLOCATION_FAILURES: 'Memory Allocation Failures',
    INCONSISTENT_MEMORY_STATE: 'Inconsistent Memory State',
    EXCESSIVE_MEMORY_FRAGMENTATION: 'Excessive Memory Fragmentation',
    MEMORY_BALANCE_ISSUES: 'Memory Balance Issues',
    MEMORY_ALLOCATION_COST: 'Memory Allocation Cost',
    EXCESSIVE_OBJECT_CREATION: 'Excessive Object Creation',
    INSUFFICIENT_MEMORY_BLOCKS: 'Insufficient Memory Blocks',
    INSUFFICIENT_MEMORY_FOR_TASKS: 'Insufficient Memory for Tasks',
    SLOW_MEMORY_ACCESS: 'Slow Memory Access',
    MEMORY_CONTENTION: 'Memory Contention',
    FREQUENT_MEMORY_REALLOCATION: 'Frequent Memory Reallocation',
    OUT_OF_MEMORY_ERRORS: 'Out of Memory Errors',
    MEMORY_LIMIT_EXCEEDANCE: 'Memory Limit Exceedance',
    DYNAMIC_MEMORY_ALLOCATION: 'Dynamic Memory Allocation',
    MEMORY_DUMP_ISSUES: 'Memory Dump Issues',
    MEMORY_CONCURRENCY_ISSUES: 'Memory Concurrency Issues',
    UNRELEASED_MEMORY_OBJECTS: 'Unreleased Memory Objects',
    MEMORY_CONSUMPTION_ISSUES: 'Memory Consumption Issues',
    EXCESSIVE_STACK_USAGE: 'Excessive Stack Usage',
    MEMORY_SHRINKING: 'Memory Shrinking',
    SUSPENDED_MEMORY_ALLOCATION: 'Suspended Memory Allocation',
    MEMORY_ALLOCATION_CYCLES: 'Memory Allocation Cycles',
    CACHE_MEMORY_LEAKS: 'Cache Memory Leaks',
    MEMORY_ALIGNMENT_ISSUES: 'Memory Alignment Issues',
    MEMORY_ADDITION_FAILURES: 'Memory Addition Failures',
    MEMORY_ALLOCATOR_FAILURE: 'Memory Allocator Failure',
    EXCESSIVE_ALLOCATED_MEMORY_SIZE: 'Excessive Allocated Memory Size',
    MEMORY_GARBAGE_COLLECTION: 'Memory Garbage Collection',
    MEMORY_BLOCK_REUSE_ISSUES: 'Memory Block Reuse Issues',
    MEMORY_USAGE_OPTIMIZATION: 'Memory Usage Optimization',
    INSUFFICIENT_MEMORY_FOR_CACHING: 'Insufficient Memory for Caching',
    MEMORY_BLOCK_DEALLOCATION_ISSUES: 'Memory Block Deallocation Issues',
    SLOW_MEMORY_FREEING: 'Slow Memory Freeing',
    MEMORY_BLOCK_FRAGMENTATION: 'Memory Block Fragmentation',
    UNMANAGED_MEMORY_USAGE: 'Unmanaged Memory Usage',
    FREQUENT_MEMORY_CLEANUP: 'Frequent Memory Cleanup',
    MEMORY_ALLOCATOR_OVERLOAD: 'Memory Allocator Overload',
    INADEQUATE_MEMORY_SWAP: 'Inadequate Memory Swap',
    MEMORY_USAGE_PATTERN_ISSUES: 'Memory Usage Pattern Issues',
    INSUFFICIENT_BUFFER_ALLOCATIONS: 'Insufficient Buffer Allocations',
    MEMORY_POOL_REUSE: 'Memory Pool Reuse',
    MEMORY_HIT_RATE: 'Memory Hit Rate',
    MEMORY_ALLOCATION_EXPANSION: 'Memory Allocation Expansion',
    LACK_OF_MEMORY_RESOURCE_POOL: 'Lack of Memory Resource Pool',
    MEMORY_ACCESS_SPEED: 'Memory Access Speed',
    MEMORY_PARTITIONING_ISSUES: 'Memory Partitioning Issues',
    UNPREDICTABLE_MEMORY_USAGE: 'Unpredictable Memory Usage',
    CACHE_MEMORY_THROTTLING: 'Cache Memory Throttling',
    EXCESSIVE_MEMORY_CONSUMPTION_BY_THREADS: 'Excessive Memory Consumption by Threads',
    MEMORY_FRAGMENTATION_DUE_TO_CACHE: 'Memory Fragmentation Due to Cache',
    HEAVY_MEMORY_LOAD: 'Heavy Memory Load',
    MEMORY_USAGE_DISTRIBUTION_ISSUES: 'Memory Usage Distribution Issues',
    MEMORY_SIZE_INCONSISTENCY: 'Memory Size Inconsistency',
    MEMORY_OVERSUBSCRIPTION: 'Memory Oversubscription',
    MULTIPLE_MEMORY_ALLOCATION_ISSUES: 'Multiple Memory Allocation Issues',
    MEMORY_OVERCOMMIT: 'Memory Overcommit',
    HIGH_MEMORY_CONSUMPTION_RATES: 'High Memory Consumption Rates',
    UNOPTIMIZED_MEMORY_ACCESS: 'Unoptimized Memory Access',
    INSUFFICIENT_MEMORY_SWAP_SPACE: 'Insufficient Memory Swap Space',
    MEMORY_CONSUMPTION_MONITORING: 'Memory Consumption Monitoring',
    MEMORY_ALLOCATION_VIOLATIONS: 'Memory Allocation Violations',
    CACHE_MEMORY_CONSUMPTION: 'Cache Memory Consumption',
    INSUFFICIENT_MEMORY_FOR_CACHE: 'Insufficient Memory for Cache',
    EXCESSIVE_MEMORY_GATHERING: 'Excessive Memory Gathering',
    MEMORY_LEAK_ANALYSIS_FAILURE: 'Memory Leak Analysis Failure',
    EXCESSIVE_MEMORY_READS: 'Excessive Memory Reads',
    EXCESSIVE_MEMORY_WRITES: 'Excessive Memory Writes',
    MEMORY_COMPACTION_ISSUES: 'Memory Compaction Issues',
    MEMORY_CACHE_EVICTION: 'Memory Cache Eviction',
    MEMORY_OVERUSE_BY_APPLICATION: 'Memory Overuse by Application',
    INSUFFICIENT_MEMORY_ALLOCATION_FOR_THREADS: 'Insufficient Memory Allocation for Threads',
    MEMORY_CONFLICTS: 'Memory Conflicts',
    MEMORY_COMPRESSOR_FAILURE: 'Memory Compressor Failure',
    MEMORY_USAGE_FLUCTUATIONS: 'Memory Usage Fluctuations',
    EXCESSIVE_MEMORY_FREQUENCY: 'Excessive Memory Frequency',
    MEMORY_OVERUSE_ALERTS: 'Memory Overuse Alerts',
    MEMORY_THROTTLING_BY_SYSTEM: 'Memory Throttling by System',
    MEMORY_ALLOCATOR_MEMORY_FAILURES: 'Memory Allocator Memory Failures',
    MEMORY_TRACKING_ISSUES: 'Memory Tracking Issues',
    MEMORY_CONFIGURATION_ISSUES: 'Memory Configuration Issues',
    MEMORY_LATENCY: 'Memory Latency',
    HIGH_MEMORY_LATENCY: 'High Memory Latency'
};


// فئات تحليل استهلاك البطارية
const BATTERY_CATEGORIES = {
    BACKGROUND_PROCESSES: 'Background Processes',
    LOCATION_SERVICES: 'Location Services',
    NETWORK_OPERATIONS: 'Network Operations',
    SENSOR_USAGE: 'Sensor Usage',
    WAKE_LOCKS: 'Wake Locks',
    ANIMATIONS_AND_GRAPHICS: 'Animations and Graphics',
    DISPLAY_BRIGHTNESS: 'Display Brightness',
    APP_REFRESH_INTERVALS: 'App Refresh Intervals',
    MULTITASKING: 'Multitasking',
    GPS_USAGE: 'GPS Usage',
    WIFI_USAGE: 'Wi-Fi Usage',
    MOBILE_DATA_USAGE: 'Mobile Data Usage',
    BLUETOOTH_USAGE: 'Bluetooth Usage',
    BACKGROUND_APP_REFRESH: 'Background App Refresh',
    SCREEN_ON_TIME: 'Screen On Time',
    APP_PUSH_NOTIFICATIONS: 'App Push Notifications',
    VIDEO_PLAYBACK: 'Video Playback',
    AUDIO_PLAYBACK: 'Audio Playback',
    PHOTO_CAPTURE: 'Photo Capture',
    GAMEPLAY: 'Gameplay',
    APP_SYNCING: 'App Syncing',
    SYSTEM_UPDATES: 'System Updates',
    APP_NOTIFICATIONS: 'App Notifications',
    NETWORK_CONNECTIVITY: 'Network Connectivity',
    DATABASE_OPERATIONS: 'Database Operations',
    WIFI_SCANNING: 'Wi-Fi Scanning',
    MOBILE_SIGNAL_STRENGTH: 'Mobile Signal Strength',
    LOCATION_ACCURACY: 'Location Accuracy',
    APP_IDLE_MODE: 'App Idle Mode',
    DISPLAY_REFRESH_RATE: 'Display Refresh Rate',
    APP_BACKGROUND_ACTIVITY: 'App Background Activity',
    MEMORY_CACHING: 'Memory Caching',
    CPU_PROCESSING: 'CPU Processing',
    BATTERY_SAVING_MODE: 'Battery Saving Mode',
    HARDWARE_ACCELERATION: 'Hardware Acceleration',
    SOFTWARE_UPDATES: 'Software Updates',
    DATA_SYNC_FREQUENCY: 'Data Sync Frequency',
    NETWORK_TRAFFIC: 'Network Traffic',
    INSTANT_MESSAGING: 'Instant Messaging',
    CLOUD_STORAGE_SYNC: 'Cloud Storage Sync',
    BROWSER_TABS: 'Browser Tabs',
    APP_WIDGETS: 'App Widgets',
    MULTIMEDIA_TRANSCODING: 'Multimedia Transcoding',
    SCREEN_RESOLUTION: 'Screen Resolution',
    APP_PERMISSION_REQUESTS: 'App Permission Requests',
    LOCATION_BACKGROUND_UPDATES: 'Location Background Updates',
    APP_BACKGROUND_TASKS: 'App Background Tasks',
    EXTERNAL_STORAGE_ACCESS: 'External Storage Access',
    SYSTEM_LOGGING: 'System Logging',
    FILE_SHARING: 'File Sharing',
    VPN_USAGE: 'VPN Usage',
    BATTERY_CHARGING_STATUS: 'Battery Charging Status',
    DISPLAY_ON_INTERVALS: 'Display On Intervals',
    SYSTEM_CLEANUP: 'System Cleanup',
    PERFORMANCE_MONITORING: 'Performance Monitoring',
    BACKGROUND_IMAGE_PROCESSING: 'Background Image Processing',
    CLOUD_SYNCING: 'Cloud Syncing',
    APP_OPENED_TIME: 'App Opened Time',
    DATA_USAGE_LIMIT: 'Data Usage Limit',
    MULTIPLE_CONNECTIONS: 'Multiple Connections',
    SYSTEM_OPTIMIZATION: 'System Optimization',
    NETWORK_EFFICIENCY: 'Network Efficiency',
    TASKS_IN_PROGRESS: 'Tasks in Progress',
    VIDEO_STREAMING: 'Video Streaming',
    APP_CRASHES: 'App Crashes',
    BACKGROUND_SYNC: 'Background Sync',
    OVERHEATING: 'Overheating',
    SENSOR_EVENT_HANDLING: 'Sensor Event Handling',
    INSTANT_APP_USAGE: 'Instant App Usage',
    CONNECTION_HANDLING: 'Connection Handling',
    NOTIFICATION_FREQUENCY: 'Notification Frequency',
    BACKGROUND_LOCATION_UPDATES: 'Background Location Updates',
    DEVICE_SLEEP_MODE: 'Device Sleep Mode',
    USER_ACTIVITY_DETECTION: 'User Activity Detection',
    HARDWARE_MONITORING: 'Hardware Monitoring',
    FILE_DOWNLOADS: 'File Downloads',
    SYSTEM_BOOT_UP: 'System Boot-up',
    LOCATION_ACCURACY_MODE: 'Location Accuracy Mode',
    DATA_ENCRYPTION: 'Data Encryption',
    BROWSER_HISTORY_SYNC: 'Browser History Sync',
    SCREEN_TIMEOUT: 'Screen Timeout',
    CONNECTED_DEVICES: 'Connected Devices',
    APP_CACHE_CLEARING: 'App Cache Clearing',
    CAMERA_USAGE: 'Camera Usage',
    EXTERNAL_SERVICE_REQUESTS: 'External Service Requests',
    USER_INPUT_METHODS: 'User Input Methods',
    CLOUD_BACKUP: 'Cloud Backup',
    IMAGE_COMPRESSION: 'Image Compression',
    VIDEO_RECORDING: 'Video Recording',
    APP_UPDATES: 'App Updates',
    CONNECTIVITY_SETTINGS: 'Connectivity Settings',
    DEVICE_POWER_MODE: 'Device Power Mode',
    MOBILE_PLATFORM_OPTIMIZATION: 'Mobile Platform Optimization',
    INCREASED_REFRESH_INTERVALS: 'Increased Refresh Intervals',
    SYSTEM_RESTARTS: 'System Restarts',
    SERVICE_DISCOVERY: 'Service Discovery',
    NETWORK_PING: 'Network Ping',
    DATA_USAGE_OPTIMIZATION: 'Data Usage Optimization',
    CONTENT_LOADING: 'Content Loading',
    DYNAMIC_SCREEN_BRIGHTNESS: 'Dynamic Screen Brightness',
    APP_RUNNING_IN_BACKGROUND: 'App Running in Background',
    THROTTLED_NETWORK_CONNECTIONS: 'Throttled Network Connections',
    SYSTEM_RESOURCE_CONSUMPTION: 'System Resource Consumption',
    NETWORK_DELAY: 'Network Delay',
    BACKGROUND_NETWORK_CONNECTION: 'Background Network Connection',
    SLEEP_MODE_EFFICIENCY: 'Sleep Mode Efficiency',
    CPU_HEAT_MANAGEMENT: 'CPU Heat Management',
    BACKGROUND_AUDIO_PLAYBACK: 'Background Audio Playback',
    SYSTEM_IDLE_MODE: 'System Idle Mode',
    USER_NOTIFICATIONS: 'User Notifications',
    APP_AUTOMATIC_UPDATES: 'App Automatic Updates',
    USER_INTERFACE_ANIMATIONS: 'User Interface Animations',
    SIGNAL_STRENGTH_ADJUSTMENTS: 'Signal Strength Adjustments',
    APP_LOADER_SCREEN: 'App Loader Screen',
    CACHING_LAYER: 'Caching Layer',
    APP_CLEANUP_ON_EXIT: 'App Cleanup on Exit',
    FILE_CACHING: 'File Caching',
    DEVICE_GYROSCOPE_USAGE: 'Device Gyroscope Usage',
    APP_DEBUGGING_MODE: 'App Debugging Mode',
    REALTIME_DATA_SYNC: 'Real-time Data Sync',
    DEVICE_HEAT_MANAGEMENT: 'Device Heat Management',
    CONTENT_FETCHING: 'Content Fetching',
    SYSTEM_TRACES: 'System Traces',
    SYSTEM_UPTIME: 'System Uptime',
    WIRED_NETWORK_USAGE: 'Wired Network Usage',
    MOBILE_APP_SYNCING: 'Mobile App Syncing',
    SYSTEM_BACKGROUND_PROCESSING: 'System Background Processing'
};

// تصدير جميع الثوابت
module.exports = {
    MOBILE_APP_TYPES,
    RISK_CATEGORIES,
    SEVERITY_LEVELS,
    SECURITY_RISKS,
    MOBILE_RISKS,
    MOBILE_RISKS_2014,
    APP_THREATS,
    PERFORMANCE_CATEGORIES,
    MEMORY_CATEGORIES,
    BATTERY_CATEGORIES,
};